# fly.toml app configuration file for book-management-solitary-frog-2943
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'book-management-solitary-frog-2943'
primary_region = 'sin'

[build]
  # Optional: Specify builder if needed
  # builder = "heroku/buildpacks:20"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  # If you need persistent storage, uncomment and configure this
  # source = "data"
  # destination = "/data"

[deploy]
  # Optional: deployment strategy
  # strategy = "immediate"