@baseUrl = http://ec2-107-21-140-191.compute-1.amazonaws.com:3000/api

### REGISTER USER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@example.com",
  "password": "securepassword"
}

### LOGIN USER
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "securepassword"
}

### CREATE AUTHOR
POST {{baseUrl}}/authors
Content-Type: application/json

{
  "name": "John Doe",
  "bio": "Author of several books"
}

##### GET AUTHORS
GET  {{baseUrl}}/authors

### CREATE BOOK
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "Harry Potter and the Chamber of Secrets",
  "description": "The second book in the Harry Potter series",
  "isbn": "9780747538486",
  "author": "68225a54f9f5f748df31b32f",
  "publishedDate": "1998-07-02"
}


#### GET BOOKS WITH PAGINATION
GET {{baseUrl}}/books?page=1&limit=20

### GET BOOKS WITH PAGINATION
GET {{baseUrl}}/books?page=2&limit=20

